[package]
name = "miny"
version = "1.0.0"
edition = "2021"
authors = ["1e1001"]
description = "Box<T> with small value optimization"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/miny"
homepage = "https://github.com/1e1001/miny"
repository = "https://github.com/1e1001/miny"
